// RootLayout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TRPCProvider from "./components/Provider";
import ThemeToggle from "./components/ThemeToggle";
import { Providers } from "./components/Theme-context";

import AuthProvider from "./components/AuthProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-gray-100 text-gray-900 dark:bg-gray-900 dark:text-white

`}
            >
                <Providers>
                    <TRPCProvider>
                        <AuthProvider>
                            {children}
                            <ThemeToggle />
                            <Toaster position="top-right" />
                        </AuthProvider>
                    </TRPCProvider>
                </Providers>
            </body>
        </html>
    );
}
