// RootLayout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TRPCProvider from "./components/Provider";
import ThemeToggle from "./components/ThemeToggle";
import { Providers } from "./components/Theme-context";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-black via-transparent to-black dark:bg-gradient-to-br dark:from-black dark:via-gray-800 dark:to-black`}
            >
                <Providers>
                    <TRPCProvider>
                        {children}
                        <ThemeToggle />
                    </TRPCProvider>
                </Providers>
            </body>
        </html>
    );
}
